export const APP_VERSION = '3.1.0';

export const ENABLE_REDUX_DEV_TOOLS = true;

export const THEMES = {
  LIGHT: 'LIGHT'
};

console.log(process.env);

const {
  REACT_APP_SERVER_URL,
  REACT_APP_THRESHOLD_ENGINEER,
  REACT_APP_THRESHOLD_MANUFACTURER,
  REACT_APP_THRESHOLD_PACKAGER,
  REACT_APP_THRESHOLD_STERILIZER,
  REACT_APP_THRESHOLD_SHIPPER
} = process.env;
export const SERVER_URL = REACT_APP_SERVER_URL;

export const THRESHOLD_ENGINEER = REACT_APP_THRESHOLD_ENGINEER;
export const THRESHOLD_MANUFACTURER = REACT_APP_THRESHOLD_MANUFACTURER;
export const THRESHOLD_PACKAGER = REACT_APP_THRESHOLD_PACKAGER;
export const THRESHOLD_STERILIZER = REACT_APP_THRESHOLD_STERILIZER;
export const THRESHOLD_SHIPPER = REACT_APP_THRESHOLD_SHIPPER;

//export const SERVER_URL = 'https://aprevo-staging.presstigers.dev:4006';
//export const SERVER_URL = 'https://aprevo.presstigers.dev:4005';
